# Generated by Django 2.2.19 on 2022-10-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_imgmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='iniciomodelnk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='hotels/images')),
            ],
        ),
    ]
