# Generated by Django 2.2.19 on 2022-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_iniciomodelnk'),
    ]

    operations = [
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('imageperfil', models.ImageField(upload_to='hotels/images')),
                ('slide', models.ImageField(upload_to='hotels/images')),
                ('slide1', models.ImageField(upload_to='hotels/images')),
                ('slide2', models.ImageField(upload_to='hotels/images')),
            ],
        ),
    ]
