# Generated by Django 2.2.19 on 2022-10-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_departamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='turi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
